# Generated by Django 3.0.4 on 2020-03-31 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0008_product_opinions'),
    ]

    operations = [
        migrations.AddField(
            model_name='opinion',
            name='opinion_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='opinion',
            name='purchase_date',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='opinion',
            name='purchased',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='opinion',
            name='review_date',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='opinion',
            name='usefull',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='opinion',
            name='useless',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
