# Generated by Django 3.0.4 on 2020-03-31 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0009_auto_20200331_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='opinion',
            name='content',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
