# Generated by Django 3.0.4 on 2020-04-03 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0010_opinion_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='min_img_1',
            field=models.CharField(default=12, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='min_img_2',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='min_img_3',
            field=models.CharField(default='cadas', max_length=150),
            preserve_default=False,
        ),
    ]
