# Generated by Django 3.0.4 on 2020-04-04 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0011_auto_20200403_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='min_img_1',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='min_img_2',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='min_img_3',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
